# Generated by Django 5.0.4 on 2024-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appyuvan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pimage',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'shoes'), (3, 'Cloths')]),
        ),
    ]
